### ISSUE TITLE
User names are not saved

### ISSUE THREAD

**Issue by Genteure** [netbirdio/dashboard#105]
Tested on https://app.netbird.io/users

![image](https://user-images.githubusercontent.com/11240579/201486660-e4270c36-7936-4043-af54-58555a2f94b9.png)

**Comment by braginini** [comment]
Hey @Genteure 

The reason the name can't be edited is that it is coming from the IdP. When you signed up with Google, for instance, we fetched the name and therefore we can't change it. 

It might make sense to just disable name editing.

**Comment by timwsuqld** [comment]
It would be nice to have a description field then, as the username from Google IDP is junk for working out which user is which.
