### ISSUE TITLE
Allow filtering peers by groups

### ISSUE THREAD

**Issue by timwsuqld** [netbirdio/dashboard#110]
As we use groups for ACLs, it would be nice to be able to filter the peers list by groups, so we can easily see which peers an ACL applies to.

**Comment by braginini** [comment]
This totally makes sense! Thank you @timwsuqld 

We need to figure out how to build this filter in the UI. Do you have any ideas?

**Comment by timwsuqld** [comment]
Even just a dropdown to select tags, like you currently use for assigning tags, to filter for all hosts with that tag. Doesn't need to be complicated, and even if it's limited to searching for 1 tag, that will be enough for most cases.

**Comment by braginini** [comment]
@timwsuqld 
Just merged basic peer filtering by groups. 
The search bar supports group names -> just type in the group name.

We will later support a more sophisticated filter where one would be able to choose groups from the list.
