### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by a7g4** [netbirdio/dashboard#153]
It doesn't seem like there is a way to delete users that have been removed from the OIDC endpoint?

Am I missing something obvious?

**Comment by gigovich** [comment]
No, you are right. There is no functionality to remove users. You need to disable user on the IDP. We have an IDP sync feature in the roadmap for future releases.

**Comment by a7g4** [comment]
Thanks! Do you want me to close this issue (and link to a different issue?) or leave it open?

**Comment by mlsmaycon** [comment]
Lets leave it open @a7g4 when we add the function we will close it automatically

**Comment by braginini** [comment]
Done in
https://github.com/netbirdio/dashboard/pull/184.
Though it is not possible to delete a user - just block.
