### ISSUE TITLE
Update access control layout

### ISSUE THREAD

**Issue by braginini** [netbirdio/dashboard#197]
Update the layout of the Access Controls tab:

1. Table view. Impotant notes:
- If there are more than 2 ports in the list, display the rest as +N (e.g., +5 like in the screenshot) 
- Port ranges are not supported yet - no need to implement

![image](https://github.com/netbirdio/dashboard/assets/700848/d25584b7-acf1-408c-9d2b-ad7f14160985)

2. Add rule popup
![image](https://github.com/netbirdio/dashboard/assets/700848/b34373c7-4e11-463c-a545-a764e8f2e351)
When add description clicked:
![image](https://github.com/netbirdio/dashboard/assets/700848/482ea2f8-4b0f-4f26-8c36-64fdc864bf30)

Important notes:
- When one arrow is selected in either direction, then paint it in blue. If both selected - green. See screenshots above.
- Port ranges are not supported yet - no need to implement

3. Rule view:

![image](https://github.com/netbirdio/dashboard/assets/700848/a2ddbdab-9f8e-4378-8cfc-9334e6aab469)

With add description clicked

![image](https://github.com/netbirdio/dashboard/assets/700848/56635dd2-0154-412f-bc30-9681d505664b)

- Port ranges are not supported yet - no need to implement

**Comment by saroojbkhari** [comment]
Can I ask you to do somehting additional? We need a validation for ports.
I will ask the backend guy to do the validation on the API but we need to do it in the UI as well.
Port should be in range (0;65535]
65535 inclusive but 0 is not valid

**Comment by saroojbkhari** [comment]
When protocol ALL is selected - disable ports. We can't control ports in this case
When protocol ALL is selected - set the arrows to Bi-directional meaning the green arrow between the source and destination
