### ISSUE TITLE
Local startup problem

### ISSUE THREAD

**Issue by HKbool** [netbirdio/dashboard#317]
local development error

![QQ截图20240130142803](https://github.com/netbirdio/dashboard/assets/16604879/d5e04afb-911a-4950-9d42-0d926481c971)
Unable to configure https 

How to close auth0 ? Or run it

**Comment by HKbool** [comment]
Error after running locally
![20240130144253](https://github.com/netbirdio/dashboard/assets/16604879/d1c934da-e6fe-4096-9821-8da891604635)

**Comment by mlsmaycon** [comment]
Hello @HKbool the issue seems to be related to a wrongly set redirect URL, see the yellow box from your screenshot

If you are setting a redirect uri please just use the path

**Comment by HKbool** [comment]
@mlsmaycon  Are there any cases for local startup?  auth0 First time using

**Comment by mlsmaycon** [comment]
That's a common case for development. What would be your case for running the dashboard locally?

**Comment by mlsmaycon** [comment]
from your screenshot, you can remove the following from your .local-config.json:

  "hotjarTrackID"
  "redirectURI"
  "silentRedirectURI"
  "tokenSource"
  "dragQueryParams"

**Comment by HKbool** [comment]
After deleting the above configuration
![1111111111111111](https://github.com/netbirdio/dashboard/assets/16604879/246e8bc9-8071-4b36-872c-b637f937ea15)
auth0  How to configure

**Comment by HKbool** [comment]
![222222222229](https://github.com/netbirdio/dashboard/assets/16604879/ba7e4bae-7114-437c-9dc4-5b938e5ec707)
Current configuration

**Comment by mlsmaycon** [comment]
@HKbool can you add the forward slash to your redirect URLs: `http://localhost:3000/`


Also, just a heads up, we are about to merge V2, see the PR: https://github.com/netbirdio/dashboard/pull/316, with this change, your local config file should move to the repository root.

**Comment by HKbool** [comment]
auth0   Unable to configure http
![5555555555555](https://github.com/netbirdio/dashboard/assets/16604879/edd132b2-06d1-4a6c-a16b-68f09512e485)

**Comment by mlsmaycon** [comment]
As the error suggested, you can't set an http endpoint for login. But for NetBird, you won't need one. Just set it as the example below:
![image](https://github.com/netbirdio/dashboard/assets/7747744/3bd6229f-edc3-458d-8403-ba4a5e9e686c)
![image](https://github.com/netbirdio/dashboard/assets/7747744/94b370bd-7c85-43c6-9eab-c217a8e8999c)

**Comment by HKbool** [comment]
@mlsmaycon  Thank you very much, the problem is solved

**Comment by HKbool** [comment]
![777777777777](https://github.com/netbirdio/dashboard/assets/16604879/feb314be-3484-4ad8-867a-0ac11d73f098)
Do I need to start the management server? @mlsmaycon

**Comment by mlsmaycon** [comment]
You need a management server running. However, the error is related to an email that was not verified.

**Comment by HKbool** [comment]
Prompt for unverified email after launching program,Do you need to set other parameters?

**Comment by HKbool** [comment]
How to log in with account and password ? @mlsmaycon

**Comment by mlsmaycon** [comment]
You can create it on auth0 under the user management option. 

Then, you can also mark the user email as verified too once you are done creating it.

**Comment by HKbool** [comment]
@mlsmaycon  Have a question discussion community?

**Comment by mlsmaycon** [comment]
We have a [Slack community](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A)
