### ISSUE TITLE
Groups Issue

### ISSUE THREAD

**Issue by MacronOne** [netbirdio/dashboard#323]
Hello,

**The Problem**
In Settings > Group I see a group has one peer
![image](https://github.com/netbirdio/dashboard/assets/19657104/af5a4ca1-730d-4317-b0f4-ab7ec6ca6ca0)
But in peer I can't find the group or the peer that has that group attached
![image](https://github.com/netbirdio/dashboard/assets/19657104/683f6d01-3471-4b2f-bf34-b26490e60176)

**To Reproduce**
Don't have the information.

**Comment by bc547** [comment]
I have the same problem with a group.

Netbird thinks there are 2 peers in the bc547 group, but in reality there is only one.
The total number of peers shown on the screen is is correct in my case.

![image](https://github.com/netbirdio/dashboard/assets/7147550/52b233cd-3a4c-42e2-82e2-d6c8f9d05892)

In the management store.json file, I notice there is an empty peer ("") listed in the bc547 group:

```
                "cn2ko6ies12s7399dn2g": {
                    "ID": "cn2ko6ies12s7399dn2g",
                    "Name": "bc547",
                    "Issued": "api",
                    "Peers": [
                        "",
                        "cn2k76ies12s7399dn20"
                    ],
                    "IntegrationReference": {
                        "ID": 0,
                        "IntegrationType": ""
                    }
                }
```

I have no idea how it got there :-)

**Comment by MacronOne** [comment]
I think I know from where is my issue. 

As I don't have all the peers imported i started with Network Routes and  I Crate the groups that will have access to that route, I think from here is the issue as I just have another example:

,{"id":"cn348ko3jqvkt4kogung","issued":"api","name":"DML1","peers":null,"peers_count":1},

**Comment by mlsmaycon** [comment]
Hello @MacronOne @bc547, the issue has been fixed in the latest version.
