### ISSUE TITLE
Vendor the Inter font and use `localFont`

### ISSUE THREAD

**Issue by Tom-Hubrecht** [netbirdio/dashboard#375]
**Is your feature request related to a problem? Please describe.**
I built the dashboard for a NixOS self-hosted Netbird (c.f. https://github.com/NixOS/nixpkgs/pull/247118 ), but the build process does not have access to an internet connection as it is sandboxed. Thus, it is not possible to use the `Inter` font directly from `next/font/google`, but we have to use `localFont` instead.

**Describe the solution you'd like**
Would you be willing to vendor the Inter font in the project and switch to `localFont` ?

**Comment by heisbrot** [comment]
Hey @Tom-Hubrecht,

thanks for the request!

I see. Sure that should be no problem. I will create a quick PR for this.

Best,
Eduard
