### ISSUE TITLE
Auth0 log says "Success Login" but the dashboard login Error

### ISSUE THREAD

**Issue by Chauban** [netbirdio/dashboard#383]
**Describe the problem**

I have set the .local-config.json file as well as the auth0 setting. However, the local dev always stuck in the page just after log in, saying

 "Oops, something went wrong
There was an error logging you in.
Error: Unauthenticated" (See the image).

When I go to the auth0 page to see the log, the log says I logged in successfully. 

So confused. Where is the problem?

**Screenshots**

![auth0 log success](https://github.com/netbirdio/dashboard/assets/28912428/e99491cd-4422-42dc-974e-9cad8bcf7db3)
![dashboard log failed](https://github.com/netbirdio/dashboard/assets/28912428/3e1c6957-a18c-4c7b-9ac8-1c8a29e9629d)
[
![auth0_config](https://github.com/netbirdio/dashboard/assets/28912428/0059e0af-8a38-49f9-be1d-7e4a9df8fc1a)
](url)

**Comment by Chauban** [comment]
Anyone has developed locally please? How to solve it

**Comment by heisbrot** [comment]
Hey @Chauban ,

see the reply to your other issue here: https://github.com/netbirdio/dashboard/issues/382

Best,
Eduard
