### ISSUE TITLE
How to set up  keys Not expired

### ISSUE THREAD

**Issue by HKbool** [netbirdio/dashboard#384]
I hope to have a key that never expires

**Comment by HKbool** [comment]
![QQ截图20240522165255](https://github.com/netbirdio/dashboard/assets/16604879/1cb687bd-6f09-4897-bcb7-98f6d169be77)

**Comment by mlsmaycon** [comment]
Hello @HKbool, this is not supported by the API. However, you can generate a setup key for up to 365 days. 


What would be your use case to don't have it expiring? 

If you have concerns regarding peers, the ones activated with a setup-key without ephemeral peers enabled will not expire with the key.

**Comment by HKbool** [comment]
the ones activated with a setup-key without ephemeral peers enabled will not expire with the key.

**Comment by HKbool** [comment]
don't understand what you mean

**Comment by HKbool** [comment]
If I set 365 days, do I need to update the key after 365 days?

**Comment by mlsmaycon** [comment]
> the ones activated with a setup-key without ephemeral peers enabled will not expire with the key. don't understand what you mean

It means that by default, if you add a peer with a setup-key, and the setup-key expires, this will not remove the added peer from NetBird.

> If I set 365 days, do I need to update the key after 365 days?
> 
> Because I don’t want to update the key

You need to update the key only for new node activation. If you are using a self-hosted deployment, you can update the expiration date in the database. But there is no supporting docs for it.

**Comment by HKbool** [comment]
修改数据库中的过期日期并延长时间?

**Comment by HKbool** [comment]
What database are you using?

**Comment by HKbool** [comment]
![QQ截图20240522174751](https://github.com/netbirdio/dashboard/assets/16604879/c47e7afa-fcd2-44bb-bdf0-35be8ec832f5)
In which container is the database located?

**Comment by mlsmaycon** [comment]
Since 0.26, the default database is sqlite, if you deployed prior that, you might need to migrate from json to sqlite.

To get the sqlite file, you can list all the docker volumes and then inspect the one with `netbird_management` suffix. This will give you the host path where the file resides. After that you can backup the file and use sqlite3 command to update the DB. 

Commands example:

```shell
$ docker volume ls
...
local     tmp_netbird_management
local     tmp_netbird_zitadel_certs
...

$ docker volume inspect tmp_netbird_management
[
    {
        "CreatedAt": "2024-02-23T15:42:21+01:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "tmp",
            "com.docker.compose.version": "2.23.3",
            "com.docker.compose.volume": "netbird_management"
        },
        "Mountpoint": "/var/lib/docker/volumes/tmp_netbird_management/_data",
        "Name": "tmp_netbird_management",
        "Options": null,
        "Scope": "local"
    }
] 

$ cp /var/lib/docker/volumes/tmp_netbird_management/_data/store.db /opt/backup/

$ sqlite3 /var/lib/docker/volumes/tmp_netbird_management/_data/store.db
```

**Comment by HKbool** [comment]
store.db What is the default account password?

**Comment by HKbool** [comment]
Can I replace it directly after modification?

**Comment by HKbool** [comment]
![QQ截图20240523101157](https://github.com/netbirdio/dashboard/assets/16604879/0b3588f4-76fe-4685-86dc-e2de924eb0c9)

**Comment by HKbool** [comment]
solved @mlsmaycon

**Comment by mlsmaycon** [comment]
that's great
