### ISSUE TITLE
No option to specify multiple JWT allow groups in User Groups settings

### ISSUE THREAD

**Issue by LeszekBlazewski** [netbirdio/dashboard#391]
**Describe the problem**

When you navigate to Settings -> User Groups and try to configure JWT allow groups along with  JWT group sync there is no option to specify multiple groups. There can be only 1 group.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'Settings -> User Groups'
2. Click on 'Enable JWT group sync'
3. Input a JWT claim like 'cognito:groups'
4. Input JWT allow group(s) -> How do I input multiple groups? 

**Expected behavior**

Option to add multiple JWT allowed groups.

**Are you using NetBird Cloud?**

Self hosted netbird.

**NetBird version**

[v0.28.2](https://github.com/netbirdio/netbird/releases/tag/v0.28.2)

**Screenshots**

<img width="1013" alt="image" src="https://github.com/netbirdio/dashboard/assets/34927142/6742142a-3d7a-4eeb-a811-083072e78d5f">

**Additional context**

After a quick glance at the code it looks like everywhere (both backend and frontend) the jwt allow group field is typed as a list of strings so I do not see any reason why the input should be limited to just one group .... unless one can currently input many groups with a separator? (After testing it does not seem like it). Also it seems like the jwt allowed groups should be used as a whitelist for limiting the number of synced group from JWT token so multiple values for that whitelist seem reasonable.

It would be great if multiple jwt allow groups could be written into the input with each being separated by comma or another similar solution could be evaluated (like the group creation input box). (If the decision would be made to use a single field with comma separated values, lets update the text above the input as welll to indicate that this is supported 😄).

Great product, netbird really rocks and I am amazed every second since I started using it!

**Comment by LeszekBlazewski** [comment]
Please disregard the above, I misunderstood how the JWT allow group field works in the first place. The current setup works as it should, it's just the api specification/code that got me slightly confused since I have seen an array everywhere.

**Comment by Yanis64** [comment]
@LeszekBlazewski Hi i am facing the same issue. The API supports jwt_allow_groups as an array, but the dashboard UI only allows one group. Why is this considered normal behavior? I want to whitelist multiple groups from my IdP.

**Comment by LeszekBlazewski** [comment]
I no longer work at the place where I have configured netbird but IIRC I did it in a way where all the people who needed netbird access were part of one group in my idp and that group was used for jwt_allow_groups. All other groups should be returned in the token anyway and you should be able to use those for configuring granual access on netbird side. Its been some time since I done this and things might have changed as I am not using netbird actively anymore.
