### ISSUE TITLE
New users registered in the self-hosted system cannot receive the email verification code

### ISSUE THREAD

**Issue by BJorah** [netbirdio/dashboard#402]
I have set up a self-hosted server on my server. Now I want to register a **new management user**. I use my email address to register, but I can't receive the verification code in my email address. How should I configure it?
<img width="440" alt="微信图片_20240715114231" src="https://github.com/user-attachments/assets/2a837491-39b0-49be-a53e-1420ec1b934b">
<img width="403" alt="微信图片_20240715114248" src="https://github.com/user-attachments/assets/3b02441c-0d30-4e36-9394-0448be70c6b1">

**Comment by braginini** [comment]
hey @BJorah 
Havwe you configured SMTP in your IdP? If you are using Zitadel, here is the doc: https://zitadel.com/docs/apis/resources/admin/smtp

**Comment by BJorah** [comment]
> hey @BJorah Havwe you configured SMTP in your IdP? If you are using Zitadel, here is the doc: https://zitadel.com/docs/apis/resources/admin/smtp

How can I get this token?
![image](https://github.com/user-attachments/assets/daff1cf0-d9b9-4f60-85ba-d8a906354fdb)

**Comment by BJorah** [comment]
> hey @BJorah Havwe you configured SMTP in your IdP? If you are using Zitadel, here is the doc: https://zitadel.com/docs/apis/resources/admin/smtp

Additionally, where should I config the "SMTP in your IdP"? 
In the docker on the server？or somewhere else? (I use docker to build the server)
Please tell me which file should I config .Thanks a lot.

![image](https://github.com/user-attachments/assets/1642d38f-451c-4607-80be-8151f745e242)

**Comment by heisbrot** [comment]
Hey @BJorah,

when using Zitadel you can configure SMTP directly in the Zitadel interface. You can visit `https://yourdomain.com/ui/console/instance?id=smtpprovider` to get to the SMTP settings. 

![CleanShot 2024-07-19 at 11 12 44](https://github.com/user-attachments/assets/b57c1c7d-e4e3-42a3-a7ed-a192d0e0c45d)
