### ISSUE TITLE
Add installation guide for NixOS 22.11+/unstable

### ISSUE THREAD

**Issue by misuzu** [netbirdio/dashboard#67]
It should look something like this:

1. Edit your `configuration.nix`:
```nix
{ config, pkgs, ... }:
{
  services.netbird.enable = true; # for netbird service & CLI
  environment.systemPackages = [ pkgs.netbird-ui ]; # for GUI
}
```

2. Build and apply new configuration:
```bash
sudo nixos-rebuild switch
```

3. Run NetBird and log in the browser:
```bash
netbird up
```

4. Get your IP address:
```bash
ip addr show wt0
```

**Comment by luxus** [comment]
@misuzu are you planing to add the selfhosted part as well?

**Comment by misuzu** [comment]
> @misuzu are you planing to add the selfhosted part as well?

Official guide should work on any Linux distribution.

**Comment by luxus** [comment]
a thanks i just realised that there is just a docker version right now, maybe a hint on the directions could be helpful :D

**Comment by mlsmaycon** [comment]
hello @luxus if are you looking for a self-hosted guide, you can find it here: https://netbird.io/docs/getting-started/self-hosting

**Comment by luxus** [comment]
i saw that guide. thanks
i still hoped that someone is working on a tighter integration like 
https://nixos.wiki/wiki/WireGuard

**Comment by misuzu** [comment]
Guide for NixOS in [documentation](https://netbird.io/docs/getting-started/installation) is probably enough, closing this.
